## Makefile for the Linux kernel module.

# Define the variables of "TARGET、FILE" according to your needs.
#
# example:
# 	TARGET := hello-example
# 	FILES := test1.c test2.c test3.c
#
#   obj-m += $(TARGET).o
#	$(TARGET)-m := $(FILES:%.c=%.o)
#
####################################################

TARGET ?= hello-example
FILES ?= main.c

ifdef KERNELRELEASE

obj-m += $(TARGET).o
$(TARGET)-m := $(FILES:%.c=%.o)

# $(warning obj-m="$(obj-m)" $(TARGET)-m="$($(TARGET)-m)" )

else

KDIR ?= /lib/modules/$(shell uname -r)/build

build:
	make -C $(KDIR) M=$(shell pwd) modules
clean:
	make -C $(KDIR) M=$(shell pwd) clean

test: build
	insmod $(TARGET).ko
	rmmod $(TARGET)

endif